[workspace]
authors = ["maulikmadhavi <maulikmadhavi@gmail.com>"]
channels = ["conda-forge"]
name = "pandas"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12.10"

[pypi-dependencies]
pandas = ">=2.3.2, <3"
fuzzywuzzy = ">=0.18.0, <0.19"
tabulate = ">=0.9.0, <0.10"
